### PR TITLE
Manually upgraded libpd by copying over all relevant files from that repo.

### PR DESCRIPTION
**Pull request by chr15m**

### CODE REVIEW

**Comment by danomatika** [comment]
I'm going to transition to using libpd as a submodule, so let me wait on this.

**Comment by danomatika** [comment]
I hope you didn't have to do this manually. I have a script which does all this which I'm updating now.

**Comment by danomatika** [comment]
There were a few other things that needed to be done, so I didn't accept the PR. The Xcode project needed to be updated and there were also a few pd src pfft files which needed to be removed since they were replaced by new ones. It might have compiled as is, but could lead to future problems.

**Comment by chr15m** [comment]
Agh, sorry for creating more work for you during your thesis! Thanks very much for doing that anyway.

**Pull request closed without merging**
