### PR TITLE
Add handling of processed sensor data - solves #81

### PR DESCRIPTION
**Pull request by brizolara**
OK, cancelled [the previous one](https://github.com/danomatika/PdParty/pull/91)

Processed motion data + sample patch:

The new 6 global receivers cited in #81 were added, along with all related messages, in the same way that the raw sensor data is handled. #heading and #magneticfield were not added.
#processedmotion was added also (which corresponds to CMDeviceMotion). If processed motion is disabled/unavailable, the 6 aforementioned quantities can't be retrieved.
A patch elemental-rain was added to /res/patches/samples/pdparty/, that receives #orientationeuler and sets #processedmotion
Timer instead of queue:

In the Sensors class, I implemented the autoUpdates of the processed data with a dedicate queue instead of the main queue.

The added patch (Elemental - Rain) uses euler angles to control synthesis of rain.

I hope it's useful,

Tiago

### CODE REVIEW

**Comment by danomatika** [comment]
Additionally, once we arrive on the user API (event naming and format), we need to update the user guide and associated patches in the composer pack. Perhaps a simple set of example patches for the composerpack "cookbook" would also be good, ie. beginner oriented usage examples like "here is how to use motion events for ...". I think the rain example will be great but perhaps a bit harder to beginners to dive into?

**Comment by danomatika** [comment]
As noted in my post to #81, I have implemented a subset of these events in the master branch. Thanks for this PR as I used it as a helpful reference.

**Comment by brizolara** [comment]
Hey Dan, thanks for citing me in the CHANGES.txt anyway ;). I'm happy to have contributed, I myself will be using these features a lot.
I had already written 2 patches for the cookbook, updated the documentation, and simplified the Elemental-rain patch - but inserted a nasty bug and I am not having time to delve into it now...
I hope to include these in a new PR soon...

**Comment by danomatika** [comment]
> Hey Dan, thanks for citing me in the CHANGES.txt anyway ;). I'm happy to have contributed, I myself will be using these 
features a lot.

No problem. I may have written the solution in a different way, but you provided the template.

> I had already written 2 patches for the cookbook, updated the documentation, and simplified the Elemental-rain patch - but inserted a nasty bug and I am not having time to delve into it now...
> I hope to include these in a new PR soon...

Those would be nice to have, please do. Also do not forget to add your own attribution and/or licensing.

**Pull request closed without merging**
