### PR TITLE
Adds Files app support

### LINKED ISSUE #67: No Files app support?
Is there a reason why "Supports opening documents in place" property is explicitly set to `false`? iTunes file sharing and web server are quite archaic methods of file transfer from/to iOS.
Set it to `true` and Files app picked up folders without problem (well, file associations don't seem to work, but that's another issue) 
IMG_1876

### PR DESCRIPTION
**Pull request by fomalsd**
Fixes #67

### CODE REVIEW

**Comment by danomatika** [comment]
Thanks!

**Comment by danomatika** [comment]
Also, if you have it working, maybe you can add a bullet explaining basics of Files app -> PdParty to the [user guide](https://github.com/danomatika/PdParty/blob/master/doc/guide/PdParty_User_Guide.md#detailed-instructions).

**Comment by fomalsd** [comment]
Sure

**Comment by danomatika** [comment]
I finally looked into this and got it working relatively well with the latest commit.

One issue is that it's _possible_ to open single patches from other inside other apps, but permissions fail when trying to open anything else such as included abstractions or resource files. For now, PdParty will refuse to open anything outside itself and show an error asking to copy the project inside.

**Pull request merged**
